"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import axios from "axios";
import { Code } from "lucide-react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import ReactMarkdown from "react-markdown";
import { toast } from "sonner";
import * as z from "zod";

import { BotAvatar } from "@/components/bot-avatar";
import { Empty } from "@/components/empty";
import { Heading } from "@/components/heading";
import { Loader } from "@/components/loader";
import { UserAvatar } from "@/components/user-avatar";
import { Button } from "@/components/ui/button";
import { Form, FormControl, FormField, FormItem } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { useProModal } from "@/hooks/use-pro-modal";
import { cn } from "@/lib/utils";
import { codeFormSchema } from "@/schemas";
import type { ChatCompletionRequestMessage } from "openai";

type AIDetectionResult = {
  sentence: string;
  generatedProb: number;
  classification: string;
  confidenceCategory: string;
  confidenceScore: number;
};

const CodePage = () => {
  const proModal = useProModal();
  const [messages, setMessages] = useState<ChatCompletionRequestMessage[]>([]);
  const [statusCode, setStatusCode] = useState<number | null>(null);
  const [aiDetectionResult, setAiDetectionResult] = useState<AIDetectionResult[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const form = useForm<z.infer<typeof codeFormSchema>>({
    resolver: zodResolver(codeFormSchema),
    defaultValues: {
      prompt: "",
    },
  });

  // 模拟数据
  const mockData = [
    {
      sentence: "This is a test sentence generated by AI.",
      generatedProb: 0.87,
      classification: "AI",
      confidenceCategory: "high",
      confidenceScore: 0.87,
    },
    {
      sentence: "Another example sentence likely generated by AI.",
      generatedProb: 0.92,
      classification: "AI",
      confidenceCategory: "medium",
      confidenceScore: 0.92,
    },
  ];

  const onSubmit = async (values: z.infer<typeof codeFormSchema>) => {
    try {
      // 检查输入是否为 "test"，如果是则显示模拟数据
      if (values.prompt.toLowerCase() === "test") {
        setAiDetectionResult(mockData);
        setStatusCode(200); // 模拟成功的状态码
        return;
      }

      setIsLoading(true); // 开始加载时设置为 true
      const userMessage: ChatCompletionRequestMessage = {
        role: "user",
        content: values.prompt,
      };

      const newMessages = [...messages, userMessage];

      const response = await axios.post("/api/code", { text: values.prompt });

      // 设置状态码
      setStatusCode(response.status);

      const result = response.data;

      // 提取重要字段
      const processedResult = result.documents[0].sentences.map((sentence: any) => ({
        sentence: sentence.sentence,
        generatedProb: sentence.generated_prob,
        classification: result.documents[0].predicted_class,
        confidenceCategory: result.documents[0].confidence_category,
        confidenceScore: result.documents[0].confidence_score,
      }));

      // 更新消息和结果状态
      setMessages((current) => [...current, userMessage]);
      setAiDetectionResult(processedResult);
    } catch (error) {
      if (axios.isAxiosError(error)) {
        if (error.response?.status === 429) {
          toast.error("Too many requests. Please try again later.");
        } else if (error.response?.status === 403) {
          proModal.onOpen();
        } else {
          setStatusCode(error.response?.status || 500);
          toast.error("Something went wrong.");
        }
      }
      console.error("[API_ERROR]: ", error);
    } finally {
      setIsLoading(false); // 请求完成后重置加载状态
      form.reset();
    }
  };

  return (
    <div>
      <Heading
        title="Ai率检测"
        description="Generate code using descriptive text."
        icon={Code}
        iconColor="text-green-700"
        bgColor="bg-green-700/10"
      />

      <div className="px-4 lg:px-8">
        <div className="">
          <Form {...form}>
            <form
              onSubmit={form.handleSubmit(onSubmit)}
              autoComplete="off"
              autoCapitalize="off"
              className="rounded-lg border w-full p-4 px-3 md:px-6 focus-within:shadow-sm grid grid-cols-12 gap-2"
            >
              <FormField
                name="prompt"
                render={({ field }) => (
                  <FormItem className="col-span-12 lg:col-span-10">
                    <FormControl className="m-0 p-0">
                      <Input
                        className="border-0 outline-none focus-visible:ring-0 focus-visible:ring-transparent"
                        disabled={isLoading}
                        aria-disabled={isLoading}
                        placeholder="将需要检测的文本放入文本框"
                        {...field}
                      />
                    </FormControl>
                  </FormItem>
                )}
              />

              <Button
                className="col-span-12 lg:col-span-2 w-full"
                disabled={isLoading}
                aria-disabled={isLoading}
              >
                检查
              </Button>
            </form>
          </Form>
        </div>

        <div className="space-y-4 mt-4">
          {isLoading && (
            <div className="p-8 rounded-lg w-full flex items-center justify-center bg-muted">
              <Loader />
            </div>
          )}
          {/* {messages.length === 0 && !isLoading && (
            <Empty label="No conversation started." />
          )} */}
          <div className="flex flex-col-reverse gap-y-4">
            {messages.map((message, i) => (
              <div
                key={`${i}-${message.content}`}
                className={cn(
                  "p-8 w-full flex items-start gap-x-8 rounded-lg",
                  message.role === "user"
                    ? "bg-white border border-black/10"
                    : "bg-muted",
                )}
              >
                {message.role === "user" ? <UserAvatar /> : <BotAvatar />}
                <p className="text-sm">
                  <ReactMarkdown
                    components={{
                      pre: ({ node, ...props }) => (
                        <div className="overflow-auto w-full my-2 bg-black/10 p-2 rounded-lg">
                          <pre {...props} />
                        </div>
                      ),
                      code: ({ node, ...props }) => (
                        <code
                          className="bg-black/10 rounded-lg p-1"
                          {...props}
                        />
                      ),
                    }}
                    className="text-sm overflow-hidden leading-7"
                  >
                    {message.content || ""}
                  </ReactMarkdown>
                </p>
              </div>
            ))}
          </div>

          {/* 在页面显示状态码 */}
          <div className="mt-4">
            <p>
              <strong>API Status Code:</strong> {statusCode ? statusCode : "--"}
            </p>
          </div>

          {/* 在页面显示 AI 检测结果 */}
          {aiDetectionResult.length > 0 ? (
            <div className="mt-6">
              <h2 className="text-lg font-bold">AI Detection Results</h2>
              {aiDetectionResult.map((result, index) => (
                <div
                  key={index}
                  className="p-4 mt-2 border rounded-lg bg-gray-50"
                >
                  <p>
                    <strong>Sentence:</strong> {result.sentence}
                  </p>
                  <p>
                    <strong>Generated Probability:</strong>{" "}
                    {result.generatedProb.toFixed(4)}
                  </p>
                  <p>
                    <strong>Classification:</strong> {result.classification}
                  </p>
                  <p>
                    <strong>Confidence Category:</strong>{" "}
                    {result.confidenceCategory}
                  </p>
                  <p>
                    <strong>Confidence Score:</strong>{" "}
                    {result.confidenceScore.toFixed(4)}
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <div className="mt-4">
              <p>No AI detection results.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CodePage;
